import yfinance as yf
import pandas as pd 
import matplotlib.pyplot as plt  
ticker=yf.Ticker("AAPL")
data=ticker.history(period="6mo")
data["MA20"]=data["Close"].rolling(20).mean()
data["MA50"]=data["Close"].rolling(50).mean()
plt.figure(figsize=(12,6))
plt.plot(data["Close"],label="AAPL Price")
plt.plot(data["MA20"],label="20-Day Average")
plt.plot(data["MA50"],label="50-Day Average")
data["Daily Return"]=data["Close"].pct_change()
print("\nDaily Returns:")
print(data["Daily Return"].tail(10))
data["Rolling Volatility"]=data["Daily Return"].rolling(20).std()
volatility=data["Daily Return"].std()
print(f"\nVolatility(daily):{volatility:.4f}")
annual_volatility=volatility*(252**0.5)
print(f"Volatility(annualized):{annual_volatility:.4f}")
risk_free_rate=0
sharpe_ratio=(data["Daily Return"].mean()-risk_free_rate)/data["Daily Return"].std()
annual_sharpe_ratio=sharpe_ratio*(252**0.5)
print(f"Sharpe Ratio(annualized):{annual_sharpe_ratio:.4f}")
data["Cumulative Return"]=(1 + data["Daily Return"]).cumprod()
print(f"\nFinal Cumulative Return:{data['Cumulative Return'].iloc[-1]:.4f}")
plt.title("AAPL Stock Analysis")
plt.xlabel("Date")
plt.ylabel("Price($)")
plt.legend()
plt.grid()
plt.show()
plt.figure(figsize=(12,6))
plt.plot(data["Cumulative Return"],label="Cumulative Return",color="purple")
plt.title("AAPL Growth of $1 Invested")
plt.xlabel("Date")
plt.ylabel("Growth Multiple")
plt.legend()
plt.grid()
plt.show()
plt.figure(figsize=(12,6))
plt.plot(data["Rolling Volatility"],label="20-Day Rolling Volatility",color="red")
plt.title("AAPL Rolling Volatility(20-Day)")
plt.xlabel("Date")
plt.ylabel("Volatility")
plt.legend()
plt.grid()
plt.show()